//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.02 at 07:54:11 PM UTC 
//


package com.mob.serverapi.users.base;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mob.serverapi.users.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mob.serverapi.users.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetUserResponse }
     * 
     */
    public SetUserResponse createSetUserResponse() {
        return new SetUserResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ExistUserNameRequest }
     * 
     */
    public ExistUserNameRequest createExistUserNameRequest() {
        return new ExistUserNameRequest();
    }

    /**
     * Create an instance of {@link GetUserByIdResponse }
     * 
     */
    public GetUserByIdResponse createGetUserByIdResponse() {
        return new GetUserByIdResponse();
    }

    /**
     * Create an instance of {@link GetCountUserFilteredRequest }
     * 
     */
    public GetCountUserFilteredRequest createGetCountUserFilteredRequest() {
        return new GetCountUserFilteredRequest();
    }

    /**
     * Create an instance of {@link ExistUserEmailRequest }
     * 
     */
    public ExistUserEmailRequest createExistUserEmailRequest() {
        return new ExistUserEmailRequest();
    }

    /**
     * Create an instance of {@link ChangeLangPreferenceRequest }
     * 
     */
    public ChangeLangPreferenceRequest createChangeLangPreferenceRequest() {
        return new ChangeLangPreferenceRequest();
    }

    /**
     * Create an instance of {@link SetUserRequest }
     * 
     */
    public SetUserRequest createSetUserRequest() {
        return new SetUserRequest();
    }

    /**
     * Create an instance of {@link GetUserFilteredRequest }
     * 
     */
    public GetUserFilteredRequest createGetUserFilteredRequest() {
        return new GetUserFilteredRequest();
    }

    /**
     * Create an instance of {@link GetCountUserFilteredResponse }
     * 
     */
    public GetCountUserFilteredResponse createGetCountUserFilteredResponse() {
        return new GetCountUserFilteredResponse();
    }

    /**
     * Create an instance of {@link ExistUserEmailResponse }
     * 
     */
    public ExistUserEmailResponse createExistUserEmailResponse() {
        return new ExistUserEmailResponse();
    }

    /**
     * Create an instance of {@link ChangeThemePreferenceRequest }
     * 
     */
    public ChangeThemePreferenceRequest createChangeThemePreferenceRequest() {
        return new ChangeThemePreferenceRequest();
    }

    /**
     * Create an instance of {@link GetUserByIdRequest }
     * 
     */
    public GetUserByIdRequest createGetUserByIdRequest() {
        return new GetUserByIdRequest();
    }

    /**
     * Create an instance of {@link GetUserFilteredResponse }
     * 
     */
    public GetUserFilteredResponse createGetUserFilteredResponse() {
        return new GetUserFilteredResponse();
    }

    /**
     * Create an instance of {@link ChangeUserPwRequest }
     * 
     */
    public ChangeUserPwRequest createChangeUserPwRequest() {
        return new ChangeUserPwRequest();
    }

    /**
     * Create an instance of {@link InactivateUserRequest }
     * 
     */
    public InactivateUserRequest createInactivateUserRequest() {
        return new InactivateUserRequest();
    }

    /**
     * Create an instance of {@link UnblockUserResponse }
     * 
     */
    public UnblockUserResponse createUnblockUserResponse() {
        return new UnblockUserResponse();
    }

    /**
     * Create an instance of {@link GetUserRolesByUserIdRequest }
     * 
     */
    public GetUserRolesByUserIdRequest createGetUserRolesByUserIdRequest() {
        return new GetUserRolesByUserIdRequest();
    }

    /**
     * Create an instance of {@link ChangeLangPreferenceResponse }
     * 
     */
    public ChangeLangPreferenceResponse createChangeLangPreferenceResponse() {
        return new ChangeLangPreferenceResponse();
    }

    /**
     * Create an instance of {@link UnblockUserRequest }
     * 
     */
    public UnblockUserRequest createUnblockUserRequest() {
        return new UnblockUserRequest();
    }

    /**
     * Create an instance of {@link UserLoginRequest }
     * 
     */
    public UserLoginRequest createUserLoginRequest() {
        return new UserLoginRequest();
    }

    /**
     * Create an instance of {@link ActivateUserRequest }
     * 
     */
    public ActivateUserRequest createActivateUserRequest() {
        return new ActivateUserRequest();
    }

    /**
     * Create an instance of {@link GetUserRolesByUserIdResponse }
     * 
     */
    public GetUserRolesByUserIdResponse createGetUserRolesByUserIdResponse() {
        return new GetUserRolesByUserIdResponse();
    }

    /**
     * Create an instance of {@link UserRole }
     * 
     */
    public UserRole createUserRole() {
        return new UserRole();
    }

    /**
     * Create an instance of {@link ChangeUserPwResponse }
     * 
     */
    public ChangeUserPwResponse createChangeUserPwResponse() {
        return new ChangeUserPwResponse();
    }

    /**
     * Create an instance of {@link ActivateUserResponse }
     * 
     */
    public ActivateUserResponse createActivateUserResponse() {
        return new ActivateUserResponse();
    }

    /**
     * Create an instance of {@link InactivateUserResponse }
     * 
     */
    public InactivateUserResponse createInactivateUserResponse() {
        return new InactivateUserResponse();
    }

    /**
     * Create an instance of {@link UserLoginResponse }
     * 
     */
    public UserLoginResponse createUserLoginResponse() {
        return new UserLoginResponse();
    }

    /**
     * Create an instance of {@link ExistUserNameResponse }
     * 
     */
    public ExistUserNameResponse createExistUserNameResponse() {
        return new ExistUserNameResponse();
    }

    /**
     * Create an instance of {@link ChangeThemePreferenceResponse }
     * 
     */
    public ChangeThemePreferenceResponse createChangeThemePreferenceResponse() {
        return new ChangeThemePreferenceResponse();
    }

}
