//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.02 at 07:54:11 PM UTC 
//


package com.mob.serverapi.reseller.base;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mob.serverapi.reseller.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mob.serverapi.reseller.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetResellerByIdRequest }
     * 
     */
    public GetResellerByIdRequest createGetResellerByIdRequest() {
        return new GetResellerByIdRequest();
    }

    /**
     * Create an instance of {@link GetResellerByIdResponse }
     * 
     */
    public GetResellerByIdResponse createGetResellerByIdResponse() {
        return new GetResellerByIdResponse();
    }

    /**
     * Create an instance of {@link Reseller }
     * 
     */
    public Reseller createReseller() {
        return new Reseller();
    }

    /**
     * Create an instance of {@link GetResellerByUserDeviceNameRequest }
     * 
     */
    public GetResellerByUserDeviceNameRequest createGetResellerByUserDeviceNameRequest() {
        return new GetResellerByUserDeviceNameRequest();
    }

    /**
     * Create an instance of {@link RemoveResellerRequest }
     * 
     */
    public RemoveResellerRequest createRemoveResellerRequest() {
        return new RemoveResellerRequest();
    }

    /**
     * Create an instance of {@link GetResellerFilteredRequest }
     * 
     */
    public GetResellerFilteredRequest createGetResellerFilteredRequest() {
        return new GetResellerFilteredRequest();
    }

    /**
     * Create an instance of {@link GetResellerByUserDeviceNameResponse }
     * 
     */
    public GetResellerByUserDeviceNameResponse createGetResellerByUserDeviceNameResponse() {
        return new GetResellerByUserDeviceNameResponse();
    }

    /**
     * Create an instance of {@link SetResellerResponse }
     * 
     */
    public SetResellerResponse createSetResellerResponse() {
        return new SetResellerResponse();
    }

    /**
     * Create an instance of {@link SetResellerAssociationResponse }
     * 
     */
    public SetResellerAssociationResponse createSetResellerAssociationResponse() {
        return new SetResellerAssociationResponse();
    }

    /**
     * Create an instance of {@link GetResellerBalanceMovementsRequest }
     * 
     */
    public GetResellerBalanceMovementsRequest createGetResellerBalanceMovementsRequest() {
        return new GetResellerBalanceMovementsRequest();
    }

    /**
     * Create an instance of {@link GetAvailableResellerParentRequest }
     * 
     */
    public GetAvailableResellerParentRequest createGetAvailableResellerParentRequest() {
        return new GetAvailableResellerParentRequest();
    }

    /**
     * Create an instance of {@link GetResellerBalanceMovementsResponse }
     * 
     */
    public GetResellerBalanceMovementsResponse createGetResellerBalanceMovementsResponse() {
        return new GetResellerBalanceMovementsResponse();
    }

    /**
     * Create an instance of {@link ResellerBalance }
     * 
     */
    public ResellerBalance createResellerBalance() {
        return new ResellerBalance();
    }

    /**
     * Create an instance of {@link GetResellerFilteredResponse }
     * 
     */
    public GetResellerFilteredResponse createGetResellerFilteredResponse() {
        return new GetResellerFilteredResponse();
    }

    /**
     * Create an instance of {@link GetResellerParentByChildIdRequest }
     * 
     */
    public GetResellerParentByChildIdRequest createGetResellerParentByChildIdRequest() {
        return new GetResellerParentByChildIdRequest();
    }

    /**
     * Create an instance of {@link SetResellerAssociationRequest }
     * 
     */
    public SetResellerAssociationRequest createSetResellerAssociationRequest() {
        return new SetResellerAssociationRequest();
    }

    /**
     * Create an instance of {@link SetResellerRequest }
     * 
     */
    public SetResellerRequest createSetResellerRequest() {
        return new SetResellerRequest();
    }

    /**
     * Create an instance of {@link GetAvailableResellerParentResponse }
     * 
     */
    public GetAvailableResellerParentResponse createGetAvailableResellerParentResponse() {
        return new GetAvailableResellerParentResponse();
    }

    /**
     * Create an instance of {@link GetResellerParentByChildIdResponse }
     * 
     */
    public GetResellerParentByChildIdResponse createGetResellerParentByChildIdResponse() {
        return new GetResellerParentByChildIdResponse();
    }

    /**
     * Create an instance of {@link GetResellerAssociationRequest }
     * 
     */
    public GetResellerAssociationRequest createGetResellerAssociationRequest() {
        return new GetResellerAssociationRequest();
    }

    /**
     * Create an instance of {@link SetResellerBalanceMovementResponse }
     * 
     */
    public SetResellerBalanceMovementResponse createSetResellerBalanceMovementResponse() {
        return new SetResellerBalanceMovementResponse();
    }

    /**
     * Create an instance of {@link GetCountAvailableResellerParentRequest }
     * 
     */
    public GetCountAvailableResellerParentRequest createGetCountAvailableResellerParentRequest() {
        return new GetCountAvailableResellerParentRequest();
    }

    /**
     * Create an instance of {@link GetCountResellerFilteredRequest }
     * 
     */
    public GetCountResellerFilteredRequest createGetCountResellerFilteredRequest() {
        return new GetCountResellerFilteredRequest();
    }

    /**
     * Create an instance of {@link GetResellerAssociationResponse }
     * 
     */
    public GetResellerAssociationResponse createGetResellerAssociationResponse() {
        return new GetResellerAssociationResponse();
    }

    /**
     * Create an instance of {@link ResellerAssociation }
     * 
     */
    public ResellerAssociation createResellerAssociation() {
        return new ResellerAssociation();
    }

    /**
     * Create an instance of {@link RemoveResellerAssociationRequest }
     * 
     */
    public RemoveResellerAssociationRequest createRemoveResellerAssociationRequest() {
        return new RemoveResellerAssociationRequest();
    }

    /**
     * Create an instance of {@link GetResellerByUserIdResponse }
     * 
     */
    public GetResellerByUserIdResponse createGetResellerByUserIdResponse() {
        return new GetResellerByUserIdResponse();
    }

    /**
     * Create an instance of {@link GetCountResellerFilteredResponse }
     * 
     */
    public GetCountResellerFilteredResponse createGetCountResellerFilteredResponse() {
        return new GetCountResellerFilteredResponse();
    }

    /**
     * Create an instance of {@link SetResellerBalanceMovementRequest }
     * 
     */
    public SetResellerBalanceMovementRequest createSetResellerBalanceMovementRequest() {
        return new SetResellerBalanceMovementRequest();
    }

    /**
     * Create an instance of {@link RemoveResellerResponse }
     * 
     */
    public RemoveResellerResponse createRemoveResellerResponse() {
        return new RemoveResellerResponse();
    }

    /**
     * Create an instance of {@link GetResellerByUserIdRequest }
     * 
     */
    public GetResellerByUserIdRequest createGetResellerByUserIdRequest() {
        return new GetResellerByUserIdRequest();
    }

    /**
     * Create an instance of {@link GetCountAvailableResellerParentResponse }
     * 
     */
    public GetCountAvailableResellerParentResponse createGetCountAvailableResellerParentResponse() {
        return new GetCountAvailableResellerParentResponse();
    }

    /**
     * Create an instance of {@link RemoveResellerAssociationResponse }
     * 
     */
    public RemoveResellerAssociationResponse createRemoveResellerAssociationResponse() {
        return new RemoveResellerAssociationResponse();
    }

}
