//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.22 at 04:03:46 PM UTC 
//


package com.mob.serverapi.reseller.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resellerBalance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resellerBalance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resellerBalanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="debitCredit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="movementValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="movementDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resellerBalance", propOrder = {
    "resellerBalanceId",
    "debitCredit",
    "movementValue",
    "movementDate"
})
public class ResellerBalance {

    @XmlElement(required = true)
    protected String resellerBalanceId;
    @XmlElement(required = true)
    protected String debitCredit;
    protected float movementValue;
    @XmlElement(required = true)
    protected String movementDate;

    /**
     * Gets the value of the resellerBalanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResellerBalanceId() {
        return resellerBalanceId;
    }

    /**
     * Sets the value of the resellerBalanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResellerBalanceId(String value) {
        this.resellerBalanceId = value;
    }

    /**
     * Gets the value of the debitCredit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitCredit() {
        return debitCredit;
    }

    /**
     * Sets the value of the debitCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitCredit(String value) {
        this.debitCredit = value;
    }

    /**
     * Gets the value of the movementValue property.
     * 
     */
    public float getMovementValue() {
        return movementValue;
    }

    /**
     * Sets the value of the movementValue property.
     * 
     */
    public void setMovementValue(float value) {
        this.movementValue = value;
    }

    /**
     * Gets the value of the movementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovementDate() {
        return movementDate;
    }

    /**
     * Sets the value of the movementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovementDate(String value) {
        this.movementDate = value;
    }

}
