//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.22 at 04:03:46 PM UTC 
//


package com.mob.serverapi.reseller.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parentResselerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="childResselerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="actionUserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentResselerId",
    "childResselerId",
    "actionUserId"
})
@XmlRootElement(name = "setResellerAssociationRequest")
public class SetResellerAssociationRequest {

    @XmlElement(required = true)
    protected String parentResselerId;
    @XmlElement(required = true)
    protected String childResselerId;
    @XmlElement(required = true)
    protected String actionUserId;

    /**
     * Gets the value of the parentResselerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentResselerId() {
        return parentResselerId;
    }

    /**
     * Sets the value of the parentResselerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentResselerId(String value) {
        this.parentResselerId = value;
    }

    /**
     * Gets the value of the childResselerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildResselerId() {
        return childResselerId;
    }

    /**
     * Sets the value of the childResselerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildResselerId(String value) {
        this.childResselerId = value;
    }

    /**
     * Gets the value of the actionUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionUserId() {
        return actionUserId;
    }

    /**
     * Sets the value of the actionUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionUserId(String value) {
        this.actionUserId = value;
    }

}
