//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.02 at 07:54:11 PM UTC 
//


package com.mob.serverapi.dashboard.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for active complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="active">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="week" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="quarter" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "active", propOrder = {
    "day",
    "week",
    "month",
    "quarter"
})
public class Active {

    protected long day;
    protected long week;
    protected long month;
    protected long quarter;

    /**
     * Gets the value of the day property.
     * 
     */
    public long getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     */
    public void setDay(long value) {
        this.day = value;
    }

    /**
     * Gets the value of the week property.
     * 
     */
    public long getWeek() {
        return week;
    }

    /**
     * Sets the value of the week property.
     * 
     */
    public void setWeek(long value) {
        this.week = value;
    }

    /**
     * Gets the value of the month property.
     * 
     */
    public long getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     */
    public void setMonth(long value) {
        this.month = value;
    }

    /**
     * Gets the value of the quarter property.
     * 
     */
    public long getQuarter() {
        return quarter;
    }

    /**
     * Sets the value of the quarter property.
     * 
     */
    public void setQuarter(long value) {
        this.quarter = value;
    }

}
