//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:08:11 AM UTC 
//


package com.mob.serverapi.dashboard.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for global complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="global">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="notActive" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="free" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="portalDevices" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "global", propOrder = {
    "active",
    "notActive",
    "free",
    "portalDevices"
})
public class Global {

    protected long active;
    protected long notActive;
    protected long free;
    protected long portalDevices;

    /**
     * Gets the value of the active property.
     * 
     */
    public long getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(long value) {
        this.active = value;
    }

    /**
     * Gets the value of the notActive property.
     * 
     */
    public long getNotActive() {
        return notActive;
    }

    /**
     * Sets the value of the notActive property.
     * 
     */
    public void setNotActive(long value) {
        this.notActive = value;
    }

    /**
     * Gets the value of the free property.
     * 
     */
    public long getFree() {
        return free;
    }

    /**
     * Sets the value of the free property.
     * 
     */
    public void setFree(long value) {
        this.free = value;
    }

    /**
     * Gets the value of the portalDevices property.
     * 
     */
    public long getPortalDevices() {
        return portalDevices;
    }

    /**
     * Sets the value of the portalDevices property.
     * 
     */
    public void setPortalDevices(long value) {
        this.portalDevices = value;
    }

}
