//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 01:39:57 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mob.com/serverapi/dashboard/base", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mob.serverapi.dashboard.base;
