//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.22 at 05:42:16 PM UTC 
//


package com.mob.serverapi.support.base;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mob.serverapi.support.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mob.serverapi.support.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSupportFilteredRequest }
     * 
     */
    public GetSupportFilteredRequest createGetSupportFilteredRequest() {
        return new GetSupportFilteredRequest();
    }

    /**
     * Create an instance of {@link SetTicketDetailRequest }
     * 
     */
    public SetTicketDetailRequest createSetTicketDetailRequest() {
        return new SetTicketDetailRequest();
    }

    /**
     * Create an instance of {@link IsHierarchyValidResponse }
     * 
     */
    public IsHierarchyValidResponse createIsHierarchyValidResponse() {
        return new IsHierarchyValidResponse();
    }

    /**
     * Create an instance of {@link GetSupportAssociationRequest }
     * 
     */
    public GetSupportAssociationRequest createGetSupportAssociationRequest() {
        return new GetSupportAssociationRequest();
    }

    /**
     * Create an instance of {@link GetSupportByIdRequest }
     * 
     */
    public GetSupportByIdRequest createGetSupportByIdRequest() {
        return new GetSupportByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateTicketRequest }
     * 
     */
    public UpdateTicketRequest createUpdateTicketRequest() {
        return new UpdateTicketRequest();
    }

    /**
     * Create an instance of {@link RemoveSupportAssociationResponse }
     * 
     */
    public RemoveSupportAssociationResponse createRemoveSupportAssociationResponse() {
        return new RemoveSupportAssociationResponse();
    }

    /**
     * Create an instance of {@link GetTicketFilteredResponse }
     * 
     */
    public GetTicketFilteredResponse createGetTicketFilteredResponse() {
        return new GetTicketFilteredResponse();
    }

    /**
     * Create an instance of {@link Ticket }
     * 
     */
    public Ticket createTicket() {
        return new Ticket();
    }

    /**
     * Create an instance of {@link GetTicketDetailFilteredRequest }
     * 
     */
    public GetTicketDetailFilteredRequest createGetTicketDetailFilteredRequest() {
        return new GetTicketDetailFilteredRequest();
    }

    /**
     * Create an instance of {@link GetSupportAssociationResponse }
     * 
     */
    public GetSupportAssociationResponse createGetSupportAssociationResponse() {
        return new GetSupportAssociationResponse();
    }

    /**
     * Create an instance of {@link SupportAssociation }
     * 
     */
    public SupportAssociation createSupportAssociation() {
        return new SupportAssociation();
    }

    /**
     * Create an instance of {@link GetSupportParentByChildIdRequest }
     * 
     */
    public GetSupportParentByChildIdRequest createGetSupportParentByChildIdRequest() {
        return new GetSupportParentByChildIdRequest();
    }

    /**
     * Create an instance of {@link GetCountSupportFilteredRequest }
     * 
     */
    public GetCountSupportFilteredRequest createGetCountSupportFilteredRequest() {
        return new GetCountSupportFilteredRequest();
    }

    /**
     * Create an instance of {@link RemoveSupportAssociationRequest }
     * 
     */
    public RemoveSupportAssociationRequest createRemoveSupportAssociationRequest() {
        return new RemoveSupportAssociationRequest();
    }

    /**
     * Create an instance of {@link UpdateTicketResponse }
     * 
     */
    public UpdateTicketResponse createUpdateTicketResponse() {
        return new UpdateTicketResponse();
    }

    /**
     * Create an instance of {@link GetCountTicketFilteredRequest }
     * 
     */
    public GetCountTicketFilteredRequest createGetCountTicketFilteredRequest() {
        return new GetCountTicketFilteredRequest();
    }

    /**
     * Create an instance of {@link GetCountAvailableSupportParentResponse }
     * 
     */
    public GetCountAvailableSupportParentResponse createGetCountAvailableSupportParentResponse() {
        return new GetCountAvailableSupportParentResponse();
    }

    /**
     * Create an instance of {@link SetSupportAssociationResponse }
     * 
     */
    public SetSupportAssociationResponse createSetSupportAssociationResponse() {
        return new SetSupportAssociationResponse();
    }

    /**
     * Create an instance of {@link SetTicketDetailResponse }
     * 
     */
    public SetTicketDetailResponse createSetTicketDetailResponse() {
        return new SetTicketDetailResponse();
    }

    /**
     * Create an instance of {@link RemoveSupportRequest }
     * 
     */
    public RemoveSupportRequest createRemoveSupportRequest() {
        return new RemoveSupportRequest();
    }

    /**
     * Create an instance of {@link RemoveSupportResponse }
     * 
     */
    public RemoveSupportResponse createRemoveSupportResponse() {
        return new RemoveSupportResponse();
    }

    /**
     * Create an instance of {@link GetAvailableSupportParentResponse }
     * 
     */
    public GetAvailableSupportParentResponse createGetAvailableSupportParentResponse() {
        return new GetAvailableSupportParentResponse();
    }

    /**
     * Create an instance of {@link Support }
     * 
     */
    public Support createSupport() {
        return new Support();
    }

    /**
     * Create an instance of {@link GetSupportFilteredResponse }
     * 
     */
    public GetSupportFilteredResponse createGetSupportFilteredResponse() {
        return new GetSupportFilteredResponse();
    }

    /**
     * Create an instance of {@link SetSupportRequest }
     * 
     */
    public SetSupportRequest createSetSupportRequest() {
        return new SetSupportRequest();
    }

    /**
     * Create an instance of {@link GetSupportByUserIdRequest }
     * 
     */
    public GetSupportByUserIdRequest createGetSupportByUserIdRequest() {
        return new GetSupportByUserIdRequest();
    }

    /**
     * Create an instance of {@link GetCountTicketDetailFilteredResponse }
     * 
     */
    public GetCountTicketDetailFilteredResponse createGetCountTicketDetailFilteredResponse() {
        return new GetCountTicketDetailFilteredResponse();
    }

    /**
     * Create an instance of {@link GetCountSupportFilteredResponse }
     * 
     */
    public GetCountSupportFilteredResponse createGetCountSupportFilteredResponse() {
        return new GetCountSupportFilteredResponse();
    }

    /**
     * Create an instance of {@link SetSupportResponse }
     * 
     */
    public SetSupportResponse createSetSupportResponse() {
        return new SetSupportResponse();
    }

    /**
     * Create an instance of {@link SetTicketRequest }
     * 
     */
    public SetTicketRequest createSetTicketRequest() {
        return new SetTicketRequest();
    }

    /**
     * Create an instance of {@link SetTicketResponse }
     * 
     */
    public SetTicketResponse createSetTicketResponse() {
        return new SetTicketResponse();
    }

    /**
     * Create an instance of {@link SetSupportAssociationRequest }
     * 
     */
    public SetSupportAssociationRequest createSetSupportAssociationRequest() {
        return new SetSupportAssociationRequest();
    }

    /**
     * Create an instance of {@link GetCountAvailableSupportParentRequest }
     * 
     */
    public GetCountAvailableSupportParentRequest createGetCountAvailableSupportParentRequest() {
        return new GetCountAvailableSupportParentRequest();
    }

    /**
     * Create an instance of {@link GetAvailableSupportParentRequest }
     * 
     */
    public GetAvailableSupportParentRequest createGetAvailableSupportParentRequest() {
        return new GetAvailableSupportParentRequest();
    }

    /**
     * Create an instance of {@link GetSupportParentByChildIdResponse }
     * 
     */
    public GetSupportParentByChildIdResponse createGetSupportParentByChildIdResponse() {
        return new GetSupportParentByChildIdResponse();
    }

    /**
     * Create an instance of {@link GetSupportByIdResponse }
     * 
     */
    public GetSupportByIdResponse createGetSupportByIdResponse() {
        return new GetSupportByIdResponse();
    }

    /**
     * Create an instance of {@link GetSupportByUserIdResponse }
     * 
     */
    public GetSupportByUserIdResponse createGetSupportByUserIdResponse() {
        return new GetSupportByUserIdResponse();
    }

    /**
     * Create an instance of {@link GetCountTicketDetailFilteredRequest }
     * 
     */
    public GetCountTicketDetailFilteredRequest createGetCountTicketDetailFilteredRequest() {
        return new GetCountTicketDetailFilteredRequest();
    }

    /**
     * Create an instance of {@link GetTicketDetailFilteredResponse }
     * 
     */
    public GetTicketDetailFilteredResponse createGetTicketDetailFilteredResponse() {
        return new GetTicketDetailFilteredResponse();
    }

    /**
     * Create an instance of {@link TicketDetail }
     * 
     */
    public TicketDetail createTicketDetail() {
        return new TicketDetail();
    }

    /**
     * Create an instance of {@link GetTicketFilteredRequest }
     * 
     */
    public GetTicketFilteredRequest createGetTicketFilteredRequest() {
        return new GetTicketFilteredRequest();
    }

    /**
     * Create an instance of {@link GetCountTicketFilteredResponse }
     * 
     */
    public GetCountTicketFilteredResponse createGetCountTicketFilteredResponse() {
        return new GetCountTicketFilteredResponse();
    }

    /**
     * Create an instance of {@link IsHierarchyValidRequest }
     * 
     */
    public IsHierarchyValidRequest createIsHierarchyValidRequest() {
        return new IsHierarchyValidRequest();
    }

}
