//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.21 at 12:38:50 PM UTC 
//


package com.mob.serverapi.support.base;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mob.serverapi.support.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mob.serverapi.support.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCountSupportFilteredRequest }
     * 
     */
    public GetCountSupportFilteredRequest createGetCountSupportFilteredRequest() {
        return new GetCountSupportFilteredRequest();
    }

    /**
     * Create an instance of {@link GetSupportByIdRequest }
     * 
     */
    public GetSupportByIdRequest createGetSupportByIdRequest() {
        return new GetSupportByIdRequest();
    }

    /**
     * Create an instance of {@link GetSupportFilteredResponse }
     * 
     */
    public GetSupportFilteredResponse createGetSupportFilteredResponse() {
        return new GetSupportFilteredResponse();
    }

    /**
     * Create an instance of {@link Support }
     * 
     */
    public Support createSupport() {
        return new Support();
    }

    /**
     * Create an instance of {@link RemoveSupportResponse }
     * 
     */
    public RemoveSupportResponse createRemoveSupportResponse() {
        return new RemoveSupportResponse();
    }

    /**
     * Create an instance of {@link GetSupportFilteredRequest }
     * 
     */
    public GetSupportFilteredRequest createGetSupportFilteredRequest() {
        return new GetSupportFilteredRequest();
    }

    /**
     * Create an instance of {@link RemoveSupportRequest }
     * 
     */
    public RemoveSupportRequest createRemoveSupportRequest() {
        return new RemoveSupportRequest();
    }

    /**
     * Create an instance of {@link SetSupportRequest }
     * 
     */
    public SetSupportRequest createSetSupportRequest() {
        return new SetSupportRequest();
    }

    /**
     * Create an instance of {@link GetSupportByUserIdResponse }
     * 
     */
    public GetSupportByUserIdResponse createGetSupportByUserIdResponse() {
        return new GetSupportByUserIdResponse();
    }

    /**
     * Create an instance of {@link GetSupportByIdResponse }
     * 
     */
    public GetSupportByIdResponse createGetSupportByIdResponse() {
        return new GetSupportByIdResponse();
    }

    /**
     * Create an instance of {@link GetSupportByUserIdRequest }
     * 
     */
    public GetSupportByUserIdRequest createGetSupportByUserIdRequest() {
        return new GetSupportByUserIdRequest();
    }

    /**
     * Create an instance of {@link SetSupportResponse }
     * 
     */
    public SetSupportResponse createSetSupportResponse() {
        return new SetSupportResponse();
    }

    /**
     * Create an instance of {@link GetCountSupportFilteredResponse }
     * 
     */
    public GetCountSupportFilteredResponse createGetCountSupportFilteredResponse() {
        return new GetCountSupportFilteredResponse();
    }

}
