//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.03 at 05:38:10 PM UTC 
//


package com.mob.serverapi.device.base;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mob.serverapi.device.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mob.serverapi.device.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetDeviceListResponse }
     * 
     */
    public SetDeviceListResponse createSetDeviceListResponse() {
        return new SetDeviceListResponse();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link GetCountDevicesFilteredRequest }
     * 
     */
    public GetCountDevicesFilteredRequest createGetCountDevicesFilteredRequest() {
        return new GetCountDevicesFilteredRequest();
    }

    /**
     * Create an instance of {@link SetDeviceResponse }
     * 
     */
    public SetDeviceResponse createSetDeviceResponse() {
        return new SetDeviceResponse();
    }

    /**
     * Create an instance of {@link GetDeviceByIdRequest }
     * 
     */
    public GetDeviceByIdRequest createGetDeviceByIdRequest() {
        return new GetDeviceByIdRequest();
    }

    /**
     * Create an instance of {@link GetDevicesFilteredResponse }
     * 
     */
    public GetDevicesFilteredResponse createGetDevicesFilteredResponse() {
        return new GetDevicesFilteredResponse();
    }

    /**
     * Create an instance of {@link SetDeviceListRequest }
     * 
     */
    public SetDeviceListRequest createSetDeviceListRequest() {
        return new SetDeviceListRequest();
    }

    /**
     * Create an instance of {@link GetCountDevicesFilteredResponse }
     * 
     */
    public GetCountDevicesFilteredResponse createGetCountDevicesFilteredResponse() {
        return new GetCountDevicesFilteredResponse();
    }

    /**
     * Create an instance of {@link GetDevicesFilteredRequest }
     * 
     */
    public GetDevicesFilteredRequest createGetDevicesFilteredRequest() {
        return new GetDevicesFilteredRequest();
    }

    /**
     * Create an instance of {@link GetDeviceByIdResponse }
     * 
     */
    public GetDeviceByIdResponse createGetDeviceByIdResponse() {
        return new GetDeviceByIdResponse();
    }

    /**
     * Create an instance of {@link SetDeviceRequest }
     * 
     */
    public SetDeviceRequest createSetDeviceRequest() {
        return new SetDeviceRequest();
    }

}
