//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.17 at 11:41:40 AM UTC 
//


package com.mob.serverapi.notification.base;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mob.serverapi.notification.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mob.serverapi.notification.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetUserNotificationCheckedRequest }
     * 
     */
    public SetUserNotificationCheckedRequest createSetUserNotificationCheckedRequest() {
        return new SetUserNotificationCheckedRequest();
    }

    /**
     * Create an instance of {@link GetCountUserNotificationFilteredRequest }
     * 
     */
    public GetCountUserNotificationFilteredRequest createGetCountUserNotificationFilteredRequest() {
        return new GetCountUserNotificationFilteredRequest();
    }

    /**
     * Create an instance of {@link GetCountDeviceNotificationFilteredResponse }
     * 
     */
    public GetCountDeviceNotificationFilteredResponse createGetCountDeviceNotificationFilteredResponse() {
        return new GetCountDeviceNotificationFilteredResponse();
    }

    /**
     * Create an instance of {@link GetUserNotificationFilteredResponse }
     * 
     */
    public GetUserNotificationFilteredResponse createGetUserNotificationFilteredResponse() {
        return new GetUserNotificationFilteredResponse();
    }

    /**
     * Create an instance of {@link UserNotification }
     * 
     */
    public UserNotification createUserNotification() {
        return new UserNotification();
    }

    /**
     * Create an instance of {@link GetUserNotificationFilteredRequest }
     * 
     */
    public GetUserNotificationFilteredRequest createGetUserNotificationFilteredRequest() {
        return new GetUserNotificationFilteredRequest();
    }

    /**
     * Create an instance of {@link SetUserNotificationResponse }
     * 
     */
    public SetUserNotificationResponse createSetUserNotificationResponse() {
        return new SetUserNotificationResponse();
    }

    /**
     * Create an instance of {@link SetDeviceNotificationCheckedRequest }
     * 
     */
    public SetDeviceNotificationCheckedRequest createSetDeviceNotificationCheckedRequest() {
        return new SetDeviceNotificationCheckedRequest();
    }

    /**
     * Create an instance of {@link SetUserNotificationRequest }
     * 
     */
    public SetUserNotificationRequest createSetUserNotificationRequest() {
        return new SetUserNotificationRequest();
    }

    /**
     * Create an instance of {@link GetDeviceNotificationFilteredResponse }
     * 
     */
    public GetDeviceNotificationFilteredResponse createGetDeviceNotificationFilteredResponse() {
        return new GetDeviceNotificationFilteredResponse();
    }

    /**
     * Create an instance of {@link DeviceNotification }
     * 
     */
    public DeviceNotification createDeviceNotification() {
        return new DeviceNotification();
    }

    /**
     * Create an instance of {@link SetDeviceNotificationCheckedResponse }
     * 
     */
    public SetDeviceNotificationCheckedResponse createSetDeviceNotificationCheckedResponse() {
        return new SetDeviceNotificationCheckedResponse();
    }

    /**
     * Create an instance of {@link SetUserNotificationCheckedResponse }
     * 
     */
    public SetUserNotificationCheckedResponse createSetUserNotificationCheckedResponse() {
        return new SetUserNotificationCheckedResponse();
    }

    /**
     * Create an instance of {@link GetCountUserNotificationFilteredResponse }
     * 
     */
    public GetCountUserNotificationFilteredResponse createGetCountUserNotificationFilteredResponse() {
        return new GetCountUserNotificationFilteredResponse();
    }

    /**
     * Create an instance of {@link GetCountDeviceNotificationFilteredRequest }
     * 
     */
    public GetCountDeviceNotificationFilteredRequest createGetCountDeviceNotificationFilteredRequest() {
        return new GetCountDeviceNotificationFilteredRequest();
    }

    /**
     * Create an instance of {@link SetDeviceNotificationRequest }
     * 
     */
    public SetDeviceNotificationRequest createSetDeviceNotificationRequest() {
        return new SetDeviceNotificationRequest();
    }

    /**
     * Create an instance of {@link GetDeviceNotificationFilteredRequest }
     * 
     */
    public GetDeviceNotificationFilteredRequest createGetDeviceNotificationFilteredRequest() {
        return new GetDeviceNotificationFilteredRequest();
    }

    /**
     * Create an instance of {@link SetDeviceNotificationResponse }
     * 
     */
    public SetDeviceNotificationResponse createSetDeviceNotificationResponse() {
        return new SetDeviceNotificationResponse();
    }

}
